N_SUBJECTS: 15
N_RUNS: 10

N_MOVEMENTS: 7
MOVEMENTS:
  - 'Elbow_Flexion'
  - 'Elbow_Extension'
  - 'Supination'
  - 'Pronation'
  - 'Hand_Closing'
  - 'Hand_Opening'
  - 'Rest'

N_SESSIONS: 2
SESSIONS:
  - 'MOTOR-IMAGERY'
  - 'MOTOR-EXECUTION'

ZENODO_ID: '834976'
PACKAGE_DIR: "drive/MyDrive/elbow_MI/packages"
GDF_DIR: "dataset/gdf_files"
MAT_DIR: "dataset/mat_files"
DATASET_DIR: "drive/MyDrive/elbow_MI/dataset"
SIGNALS_DIR: "drive/MyDrive/elbow_MI/signals"
FEATURES_DIR: "drive/MyDrive/elbow_MI/features"

CHANNELS:
  "F3": 0
  "F1": 1
  "Fz": 2
  "F2": 3
  "F4": 4
  "FFC5h": 5
  "FFC3h": 6
  "FFC1h": 7
  "FFC2h": 8
  "FFC4h": 9
  "FFC6h": 10
  "FC5": 11
  "FC3": 12
  "FC1": 13
  "FCz": 14
  "FC2": 15
  "FC4": 16
  "FC6": 17
  "FTT7h": 18
  "FCC5h": 19
  "FCC3h": 20
  "FCC1h": 21
  "FCC2h": 22
  "FCC4h": 23
  "FCC6h": 24
  "FTT8h": 25
  "C5": 26
  "C3": 27
  "C1": 28
  "Cz": 29
  "C2": 30
  "C4": 31
  "C6": 32
  "TTP7h": 33
  "CCP5h": 34
  "CCP3h": 35
  "CCP1h": 36
  "CCP2h": 37
  "CCP4h": 38
  "CCP6h": 39
  "TTP8h": 40
  "CP5": 41
  "CP3": 42
  "CP1": 43
  "CPz": 44
  "CP2": 45
  "CP4": 46
  "CP6": 47
  "CPP5h": 48
  "CPP3h": 49
  "CPP1h": 50
  "CPP2h": 51
  "CPP4h": 52
  "CPP6h": 53
  "P3": 54
  "P1": 55
  "Pz": 56
  "P2": 57
  "P4": 58
  "PPO1h": 59
  "PPO2h": 60
  "EOG left": 61
  "EOG middle": 62
  "EOG right": 63
  "thumb near": 64
  "thumb far": 65
  "thumb index": 66
  "index near": 67
  "index far": 68
  "index middle": 69
  "middle near": 70
  "middle far": 71
  "middle ring": 72
  "ring near": 73
  "ring far": 74
  "ring little": 75
  "little near": 76
  "little far": 77
  "thumb palm": 78
  "-": 79
  "-_1": 80
  "-_2": 81
  "-_3": 82
  "hand X": 83
  "hand Y": 84
  "hand Z": 85
  "elbow X": 86
  "elbow Y": 87
  "elbow Z": 88
  "shoulder adduction": 89
  "shoulder flexion/extension": 90
  "shoulder rotation": 91
  "elbow": 92
  "pro/supination": 93
  "wrist flexion/extension": 94
  "-_4": 95
